---
# Gateway configuration
gateway_type: "{{ lookup('env', 'GATEWAY_TYPE') | default('gateway_nat', true) }}"
# Debug: Show what we get from env
gateway_type_debug: "{{ lookup('env', 'GATEWAY_TYPE') }}"

# Network configuration
network_mode: "mycelium-only"

# Port forwarding (for NAT gateway)
port_forwards: []

# Proxy configuration (for proxy gateway)
proxy_ports: [8080, 8443]
udp_ports: []
enable_ssl: false
domain_name: ""
ssl_email: ""

# Testing
enable_testing: false
