---
- name: Install HAProxy
  apt:
    name: haproxy
    state: present
    update_cache: yes
  become: true

- name: Configure HAProxy for TCP/UDP proxying
  template:
    src: haproxy.cfg.j2
    dest: /etc/haproxy/haproxy.cfg
    mode: '0644'
  become: true
  notify: restart haproxy

- name: Enable HAProxy service
  systemd:
    name: haproxy
    enabled: yes
    state: started
  become: true

- name: Configure firewall for proxy ports
  shell: nft add rule inet firewall input tcp dport { 80, 443, {{ proxy_ports | join(', ') }} } accept
  become: true
  ignore_errors: yes

- name: Install Nginx for HTTP/HTTPS reverse proxy
  apt:
    name: nginx
    state: present
    update_cache: yes
  become: true

- name: Configure Nginx reverse proxy
  template:
    src: nginx-gateway.conf.j2
    dest: /etc/nginx/sites-available/gateway
    mode: '0644'
  become: true
  notify: reload nginx

- name: Enable Nginx site
  file:
    src: /etc/nginx/sites-available/gateway
    dest: /etc/nginx/sites-enabled/gateway
    state: link
  become: true
  notify: reload nginx

- name: Remove default Nginx site
  file:
    path: /etc/nginx/sites-enabled/default
    state: absent
  become: true
  notify: reload nginx

- name: Enable Nginx service
  systemd:
    name: nginx
    enabled: yes
    state: started
  become: true

- name: Configure SSL certificates (if enabled)
  when: enable_ssl | default(false)
  block:
    - name: Install certbot for Let's Encrypt
      apt:
        name: certbot
        state: present
      become: true

    - name: Generate SSL certificate
      command: certbot --nginx -d {{ domain_name }} --non-interactive --agree-tos --email {{ ssl_email }}
      become: true
      when: domain_name is defined and ssl_email is defined

  become: true