---
- name: Install nginx for demo
  apt:
    name: nginx
    state: present
    update_cache: yes
  become: true

- name: Create gateway status page directory
  file:
    path: /var/www/gateway-demo
    state: directory
    owner: www-data
    group: www-data
    mode: '0755'
  become: true

- name: Generate gateway status page
  template:
    src: status.html.j2
    dest: /var/www/gateway-demo/index.html
    owner: www-data
    group: www-data
    mode: '0644'
  vars:
    gateway_type: "{{ gateway_type | default('gateway_nat') }}"
  become: true

- name: Configure nginx for gateway demo
  template:
    src: nginx.conf.j2
    dest: /etc/nginx/sites-available/gateway-demo
    owner: root
    group: root
    mode: '0644'
  vars:
    gateway_type: "{{ gateway_type | default('gateway_nat') }}"
    load_average: "{{ ansible_loadavg['1-min'] | default('N/A') }}"
    public_ipv4: "{{ ansible_default_ipv4.address | default('N/A') }}"
    hostname: "{{ ansible_hostname | default('gateway') }}"
    uptime_seconds: "{{ ansible_uptime_seconds | int | default(0) }}"
    memory_total_mb: "{{ ansible_memtotal_mb | int | default(0) }}"
    architecture: "{{ ansible_architecture | default('x86_64') }}"
  become: true
  notify: reload nginx

- name: Enable gateway demo site
  file:
    src: /etc/nginx/sites-available/gateway-demo
    dest: /etc/nginx/sites-enabled/gateway-demo
    state: link
  become: true
  notify: reload nginx

- name: Disable default nginx site
  file:
    path: /etc/nginx/sites-enabled/default
    state: absent
  become: true
  notify: reload nginx

- name: Start and enable nginx
  systemd:
    name: nginx
    state: started
    enabled: yes
  become: true

- name: Display gateway information
  debug:
    msg: |
      Gateway Demo Deployed Successfully!
      ===================================

      Gateway Type: {{ gateway_type | default('gateway_nat') }}
      Network: {{ network | default('test') }}
      Public IPv4: {{ ansible_default_ipv4.address }}
      Hostname: {{ ansible_hostname }}

      Demo Status Page: http://{{ ansible_default_ipv4.address }}

      Gateway Features:
      - NAT/Masquerading: Enabled
      - Firewall: Configured
      - IP Forwarding: Enabled
      - WireGuard: {{ 'Available' if wg_config is defined else 'Not configured' }}
      - Mycelium: {{ 'Available' if mycelium_ip is defined else 'Not configured' }}