---
- name: Install nginx for demo
  apt:
    name: nginx
    state: present
    update_cache: yes
  become: true

- name: Create gateway status page directory
  file:
    path: /var/www/gateway-demo
    state: directory
    owner: www-data
    group: www-data
    mode: '0755'
  become: true

- name: Generate gateway status page
  template:
    src: status.html.j2
    dest: /var/www/gateway-demo/index.html
    owner: www-data
    group: www-data
    mode: '0644'
  vars:
    gateway_type: "{{ gateway_type | default('gateway_nat') }}"
  become: true

- name: Debug variables before template
  debug:
    msg: |
      Debug variables:
      gateway_type: {{ gateway_type | default('gateway_nat') }}
      gateway_type_debug: {{ gateway_type_debug | default('NOT_SET') }}
      GATEWAY_TYPE env: {{ lookup('env', 'GATEWAY_TYPE') | default('NOT_SET') }}
      ansible_loadavg: {{ ansible_loadavg | default('N/A') }}
      ansible_hostname: {{ ansible_hostname | default('N/A') }}
      ansible_uptime_seconds: {{ ansible_uptime_seconds | default('N/A') }}
  become: true

- name: Configure nginx for gateway demo
  template:
    src: nginx.conf.j2
    dest: /etc/nginx/sites-available/gateway-demo
    owner: root
    group: root
    mode: '0644'
  become: true
  notify: reload nginx

- name: Enable gateway demo site
  file:
    src: /etc/nginx/sites-available/gateway-demo
    dest: /etc/nginx/sites-enabled/gateway-demo
    state: link
  become: true
  notify: reload nginx

- name: Disable default nginx site
  file:
    path: /etc/nginx/sites-enabled/default
    state: absent
  become: true
  notify: reload nginx

- name: Start and enable nginx
  systemd:
    name: nginx
    state: started
    enabled: yes
  become: true

- name: Display gateway information
  debug:
    msg: |
      Gateway Demo Deployed Successfully!
      ===================================

      Gateway Type: {{ gateway_type | default('gateway_nat') }}
      Network: {{ network | default('test') }}
      Public IPv4: {{ ansible_default_ipv4.address }}
      Hostname: {{ ansible_hostname }}

      Demo Status Page: http://{{ ansible_default_ipv4.address }}

      Gateway Features:
      - NAT/Masquerading: Enabled
      - Firewall: Configured
      - IP Forwarding: Enabled
      - WireGuard: {{ 'Available' if wg_config is defined else 'Not configured' }}
      - Mycelium: {{ 'Available' if mycelium_ip is defined else 'Not configured' }}