---
- name: Configure Gateway VM
  hosts: gateway
  become: yes
  roles:
    - role: gateway_common
      tags: [common]
    - role: "{{ gateway_type }}"
      tags: [gateway]

- name: Configure Internal VMs
  hosts: internal
  become: yes
  roles:
    - role: internal_common
      tags: [common]
    - role: internal_services
      tags: [services]

- name: Setup Testing Infrastructure
  hosts: all
  become: yes
  roles:
    - role: testing
      tags: [test]
  when: enable_testing | default(false)