---
- name: Configure Gateway VM
  hosts: gateway
  become: yes
  roles:
    - role: gateway_common
      tags: [common]
    - role: "{{ gateway_type }}"
      tags: [gateway]

- name: Configure Internal VMs
  hosts: internal
  become: yes
  roles:
    - role: gateway_common
      tags: [common]

- name: Setup Testing Infrastructure
  hosts: all
  become: yes
  tasks:
    - name: Include testing role when enabled
      include_role:
        name: testing
      tags: [test]
      when: enable_testing | default(false)