---
- name: Configure Gateway VM
  hosts: gateway
  become: yes
  roles:
    - role: gateway_common
      tags: [common]
    - role: "{{ gateway_type }}"
      tags: [gateway]
    - role: gateway_demo
      tags: [demo]
      when: enable_demo | default(false)

- name: Configure Internal VMs
  hosts: internal
  become: yes
  roles:
    - role: gateway_common
      tags: [common]
    - role: vm_demo
      tags: [vm-demo]
      when: enable_vm_demo | default(false)
  when: configure_internal_vms | default(false)

- name: Setup Testing Infrastructure
  hosts: all
  become: yes
  tasks:
    - name: Include testing role when enabled
      include_role:
        name: testing
      tags: [test]
      when: enable_testing | default(false)